import "@styles/globals.css";
import type { Metadata } from "next";
import { twJoin } from "tailwind-merge";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={twJoin(inter.className, "max-h-screen")}>{children}</body>
		</html>
	);
}
